//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PigeonsLibrairy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class chathistory
    {
        public int ID { get; set; }
        public int Group_ID { get; set; }
        public int Author_ID { get; set; }
        public string Message { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual group group { get; set; }
        public virtual person person { get; set; }
    }
}
