//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PigeonsLibrairy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public const string COLUMN_GROUP_ID = "group_id";
        public const string COLUMN_DESCRIPTION = "description";
        public const string COLUMN_EVENTSTART = "event_start";
        public const string COLUMN_EVENTEND = "event_end";
        public const string COLUMN_IS_COMPLETED = "is_completed";

        public int ID { get; set; }
        public string Description { get; set; }
        public int Group_ID { get; set; }
        public System.DateTime Event_Start { get; set; }
        public Nullable<System.DateTime> Event_End { get; set; }
        public bool Is_Completed { get; set; }
    
        public virtual group group { get; set; }
    }
}
