//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PigeonsLibrairy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public int Id { get; set; }
        public int Group_id { get; set; }
        public int Task_id { get; set; }
        public int Type_id { get; set; }
        public System.DateTime Date_start { get; set; }
        public System.DateTime Date_end { get; set; }
        public string Description { get; set; }
    
        public virtual group group { get; set; }
        public virtual task task { get; set; }
        public virtual type type { get; set; }
    }
}
