//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PigeonsLibrairy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        public int ID { get; set; }
        public Nullable<int> Group_ID { get; set; }
        public string FileName { get; set; }
        public string FileURL { get; set; }
        public System.DateTime Creation_Date { get; set; }
    
        public virtual group group { get; set; }
    }
}
