//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PigeonsLibrairy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class following
    {
        public const string COLUMN_PERSON_ID = "person_id";
        public const string COLUMN_GROUP_ID = "group_id";

        public int Person_Id { get; set; }
        public int Group_id { get; set; }
        public bool Is_admin { get; set; }
        public System.DateTime Last_checkin { get; set; }
        public bool Is_active { get; set; }
    
        public virtual group group { get; set; }
        public virtual person person { get; set; }
        
    }
}
