//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PigeonsLibrairy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public const string COLUMN_AUTHOR_ID = "author_id";
        public const string COLUMN_GROUP_ID = "group_id";
        public const string COLUMN_CONTENT = "content";
        public const string COLUMN_DATE_CREATED = "date_created";

        public int Id { get; set; }
        public int Author_Id { get; set; }
        public int Group_Id { get; set; }
        public string Content { get; set; }
        public System.DateTime Date_created { get; set; }
    
        public virtual group group { get; set; }
        public virtual person person { get; set; }        
    }
}
