//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PigeonsLibrairy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public person()
        {
            this.messages = new HashSet<message>();
            this.followings = new HashSet<following>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime Inscription_date { get; set; }
        public string Profile_picture_link { get; set; }
        public System.DateTime Birth_date { get; set; }
        public string Phone_number { get; set; }
        public string Organization { get; set; }
        public string Position { get; set; }
        public string Description { get; set; }

        public enum COLUMN_NAME { NAME, EMAIL, PASSWORD, INSCRIPTION_DATE, PROFILE_PICTURE_LINK, BIRTH_DATE, PHONE_NUMBER, ORGANIZATION, POSITION, DESCRIPTION, ALL }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<message> messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<following> followings { get; set; }
    }
}
