//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PigeonsLibrairy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public person()
        {
            this.messages = new HashSet<message>();
            this.followings = new HashSet<following>();
            this.assignations = new HashSet<assignation>();
            this.tasks = new HashSet<task>();
        }

        public const string COLUMN_PERSON_ID        = "person_id";
        public const string COLUMN_NAME             = "name";
        public const string COLUMN_EMAIL            = "email";
        public const string COLUMN_PASSWORD         = "password";
        public const string COLUMN_INSCRIPTION_DATE = "inscription_date";
        public const string COLUMN_BIRTH_DATE       = "birth_date";
        public const string COLUMN_PHONE_NUMBER     = "phone_number";
        public const string COLUMN_ORGANIZATION     = "organization";
        public const string COLUMN_POSITION         = "position";
        public const string COLUMN_DESCRIPTION      = "description";
        public const string COLUMN_ALL              = "all";

        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime Inscription_date { get; set; }
        public string Profile_picture_link { get; set; }
        public System.DateTime Birth_date { get; set; }
        public string Phone_number { get; set; }
        public string Organization { get; set; }
        public string Position { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<message> messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<following> followings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assignation> assignations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task> tasks { get; set; }
    }
}
