//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PigeonsLibrairy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.tasks = new HashSet<task>();
        }

        public const string COLUMN_GROUP_ID = "group_id";
        public const string COLUMN_TYPE_ID = "type_id";
        public const string COLUMN_DATE_START = "date_start";
        public const string COLUMN_DATE_END = "date_end";
        public const string COLUMN_DESCRIPTION = "description";

        public int Id { get; set; }
        public int Group_id { get; set; }
        public int Type_id { get; set; }
        public System.DateTime Date_start { get; set; }
        public System.DateTime Date_end { get; set; }
        public string Description { get; set; }
    
        public virtual group group { get; set; }
        public virtual type type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task> tasks { get; set; }
    }
}
