//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PigeonsLibrairy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public const string COLUMN_DESCRIPTION = "description";
        public const string COLUMN_DATE_DUE = "date_due";
        public const string COLUMN_IS_COMPLETED = "is_completed";
        public const string COLUMN_PROJECT_ID = "project_id";

        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime Date_due { get; set; }
        public bool Is_completed { get; set; }
        public int Project_ID { get; set; }
    
        public virtual project project { get; set; }        
    }
}
