//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PigeonsLibrairy
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Creation_date { get; set; }
        public string Description { get; set; }
        public bool Is_active { get; set; }
    }
}
