//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PigeonsLibrairy
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int Id { get; set; }
        public int Group_id { get; set; }
        public string Description { get; set; }
        public System.DateTime Date_due { get; set; }
        public bool Is_completed { get; set; }
    }
}
