<%@ Page Title="" Language="C#" MasterPageFile="~/Main.master" AutoEventWireup="true" CodeFile="Chat.aspx.cs" Inherits="Chat" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <link rel="stylesheet" href="Resources/css/Group-chat.css" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">

    <!--Script references. -->

    <!--Reference the jQuery library. -->
    <%--<script src="Scripts/jquery-2.2.2.min.js"></script>--%>

    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.0.min.js"></script>

    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>

    <div id="divContainer">
        <%--        <div id="divLogin" class="login">
            <div>
                Your Name:<br />
            <input id="txtNickName" type="text" class="textBox" />
            </div>
            <div id="divButton">
                <input id="btnStartChat" type="button" class="submitButton" value="Start Chat" />
            </div>
        </div>--%>

        <div id="divChat" class="chatRoom">
            <div class="title">
                Welcome to Chat Room [<asp:Label runat="server" ID="lblWelcomeUsername" CssClass="user-name"></asp:Label>]
                <div class="group-toggler">toggle group</div>
            </div>
            <div class="content">
                <div id="divChatWindow" class="chatWindow">
                </div>
                <div id="divusers" class="users">
                </div>
            </div>
            <div class="messageBar">
                <input class="textbox" type="text" id="txtMessage" />
                <input id="btnSendMsg" type="button" value="Send" class="submitButton" />
            </div>
        </div>
        
        <input id="hdPersondId" type="hidden" runat="server" />
        <input id="hdPersondUserName" type="hidden" runat="server" />
        <input id="hdGroupId" type="hidden" runat="server" />
    </div>
    <div class="get-message">
        <a href="#">get message</a>
    </div>
    <div class="chat-toggler">
        <a href="#">Discussion pour le groupe</a>
    </div>

    <div class="group-joiner">
        <a href="#">Join the group</a>
    </div>

    <!--Add script to update the page and send messages.-->
    <script type="text/javascript">

        /**********************************************************
                        new scripts
        **********************************************************/

        var chatHub = $.connection.chatHub;
        var messages = new Array();

        var userName;
        var roomName;
        var newMessage;

        $(function () {
            $.connection.hub.logging = true;
            $.connection.hub.start();
        });

        function joinRoom() {
            roomName = <%= hdGroupId.Value%>
            chatHub.server.joinRoom(roomName);
            //console.log(chatHub.server.countUsers());
            console.log('joining room ' + roomName);
        }

        function leaveRoom() {
            chatHub.server.joinRoom(roomName);
        }

        function getAllMessage() {
            chatHub.server.getAllMessage();
            //displayMessage("RESPONSE:");
            
        }

        function sendMessage() {
            userName = <%= hdPersondId.Value %>
            newMessage = $('#txtMessage').val();
            roomName = <%= hdGroupId.Value%>

            chatHub.server.sendMessage({ name: userName, message: newMessage, roomName: roomName });
            displayMessage("You: " + newMessage);
            newMessage = "";
        }
        chatHub.client.newMessage = onNewMessage;

        function onNewMessage(message) {
            displayMessage(message);
            //$scope.$apply();
            console.log(message);
            //if (!$("#txtMessage").is(":focus")) {
             //   toastr.info(message);
            //}
        };

        function displayMessage(message) {
            messages.push({ message: message });
            console.log(messages);
            //$('#msgContainer').append('<div>' + message + '</div>');

            $('#divChatWindow').append('<div class="message"><span class="userName">' + userName + '</span>: ' + message + '</div>');

            var height = $('#divChatWindow')[0].scrollHeight;
            $('#divChatWindow').scrollTop(height);

        }

        $("#txtMessage").keypress(function (e) {
            if (e.which == 13) {
                e.preventDefault();
                $('#btnSendMsg').click();
            }
        });

        $('#btnSendMsg').click(function () {

            var msg = $("#txtMessage").val();
            if (msg.length > 0) {

                var userName = $('#hdUserName').val();
                sendMessage();
                $("#txtMessage").val('');
            }
        });

        $(".get-message").click(function () {
            console.log(getAllMessage());

        });

        $(".chat-toggler").click(function () {
            console.log("toggle the group chat!");
            joinRoom();
            $(".chatRoom").slideToggle(200);
        });

        $(".group-toggler").click(function () {
            $(".users").slideToggle();
        });

        $(".group-joiner").click(function () {
            console.log('joining group');
            joinRoom();
        });
    </script>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolderScripts" runat="Server">
</asp:Content>