<%@ Page Title="" Language="C#" MasterPageFile="~/Main.master" AutoEventWireup="true" CodeFile="Chat.aspx.cs" Inherits="Chat" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <link rel="stylesheet" href="Resources/css/Group-chat.css" />
    <script type="text/javascript" src="Resources/js/ajax/chat.js">
    </script>
    <!-- Toastr links -->
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js" rel="stylesheet" />
    <!-- Toastr scripts -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.2/js/toastr.min.js"></script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">


    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.0.min.js"></script>

    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>

    <div id="divContainer">
     
        <input id="hdPersondId" type="hidden" runat="server" />
        <input id="hdPersondUserName" type="hidden" runat="server" />
        <input id="hdGroupId" type="hidden" runat="server" />
    </div>

    <div class="chat-toggler">
        <a href="#">Discussion pour le groupe</a>
    </div>

    <!--Add script to update the page and send messages.-->
    <script type="text/javascript" src="Resources/js/ajax/chat.js"></script>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolderScripts" runat="Server">
</asp:Content>